### ISSUE TITLE
[BUG] 홈페이지에서 정적 파일이 호출되지 않는 문제

### ISSUE THREAD

**Issue by f1v3-dev** [nhnacademy-be4-ckin/ckin-front#92]
## 🚨 어떤 버그인가요?

모든 정적 파일들이 불러지지 않고 몇개만 불러지는 버그가 발생하였습니다.

## 💥 어떤 상황에서 발생한 버그인가요?

홈페이지를 호출 할 때 불러오는 모든 정적 파일(css, js, images, favicon ...)의 문제였습니다.

`public class JwtFilter extends OncePerRequestFilter` 클래스의 동작을 생각해보면,

`OncePerRequestFilter.java`를 상속하고 있는데 해당 클래스는 무조건 1번은 실행하는 필터의 특성상 발생한 오류로
JwtFilter에서 Resource 파일이 통과(request uri = "/css/..") 하여 API서버로 계속해서 접근하는 문제가 발생하였습니다.

## 💡 해결방안
```java
    @Override
    protected void doFilterInternal(HttpServletRequest request, HttpServletResponse response, FilterChain filterChain)
            throws ServletException, IOException {

        if (isResourceFile(request.getRequestURI())) {
            filterChain.doFilter(request, response);
            return;
        }

        log.debug("request uri = {}", request.getRequestURI());

       ....

    private static boolean isResourceFile(String requestUri) {
            return requestUri.startsWith("/static") ||
                    requestUri.startsWith("/css") ||
                    requestUri.startsWith("/js") ||
                    requestUri.startsWith("/images");
        }
  ...
}
```

위와 같이 정적 리소스 파일일 경우 기존에 작성되어있던 로직을 통과하지 못하도록 return을 해줍니다.

## 👀 참고사항

> 위의 `isResourceFile(String requestUri)` 메서드에서 startWith("/css"), startWith("/js") 와 같이 잡은 이유

properties에서 `spring.mvc.static-path-pattern`의 기본 경로는 `/**`로 /resources 하위 파일로 설정됩니다.

**Comment by devhomh** [comment]
해당 이슈 반영되었으니 Close 하겠습니다 ㅎㅎ
